### ISSUE TITLE
Does historymap record tabs opened before it starts?

### ISSUE THREAD

**Issue by kaidatavis** [Vis4Sense/SenseMapExtension#137]

**Comment by kaidatavis** [comment]
Reason to include: 
- user may open a link from one of these pages, which may cause an error in historymap as it can't find the parent page.

For now, just include all the opened tabs in the historymap.

**Comment by kaidatavis** [comment]
Now all the tabs/pages opened before historyMap are included.

**Comment by Yuu-Han** [comment]
Sorry I do not know the details of previous discussion. I agree that the previous pages should be included in the list for finding the parent page, but can we have more discussion on how to show them to the user?

Currently I have to restart chrome in order to run a session without distraction from already opened tabs. It would be more convenient for me if I can choose to have all the previous tabs shown or collapsed/aggregated. For the latter case, the collapsed page can be shown when user opens a child page of it.

In addition, I remember in the sensemap paper there was a requirement on avoiding interruption, e.g., not including the commonly accessed services.

**Comment by kaidatavis** [comment]
I agree it will be good to have it as a user option to choose whether to show the tabs opened before starting HistoryMap. The way of the current implementation is mainly because it is the easiest to implement. 

Feel free to reopen this issue and make changes to the code if you want to add this user option.

**Comment by Yuu-Han** [comment]
Maybe a button to add all opened tabs to historymap, beside the restore button (#176)?

**Comment by kaidatavis** [comment]
Sounds like a good idea. 

So this 'add opened tabs' button would add all the tabs opened before running historymap to historymap, while the 'restore' button would open all the pages that were open when last close historymap?

What if historymap continuously record in the background?

**Comment by Yuu-Han** [comment]
Merged with #170.
